Project/urls.py
"""
Definition of urls for Project.
"""

from django.urls import path, include
from django.contrib import admin
from app import views


urlpatterns = [
    path('tag/<slug:tag_slug>/', views.home, name='projects_by_tag'),
    path('category/<slug:category_slug>/', views.home, name='projects_by_category'),
    path('search/', views.home, name='search'),
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('campaign/', include('campaign.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
]

campaign/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('add_project/', views.add_project, name='add_project'),
    path('edit_project/<slug:slug>/<int:id>/', views.edit_project, name='edit_project'),
    path('add_project_image/<slug:slug>/<int:id>/', views.add_project_image, name='add_project_image'),
    path('delete_project_image/', views.delete_project_image, name='delete_project_image'),
    path('edit_reward/<int:id>/', views.edit_reward, name='edit_reward'),
    path('add_reward/<slug:slug>/<int:id>/', views.add_reward, name='add_reward'),
    path('delete_reward/', views.delete_reward, name='delete_reward'),
    path('rewards/<slug:slug>/<int:id>/', views.rewards, name='rewards'),
    path('add_news/<slug:slug>/<int:id>/', views.add_news, name='add_news'),
    path('edit_news/<int:id>/', views.edit_news, name='edit_news'),
    path('news/<int:id>/', views.news, name='news'),
    path('<slug:slug>/<int:id>/', views.project, name='project')
]

campaign/models.py
from django.db import models
from django.urls import reverse
from django.core.validators import MaxValueValidator, MinValueValidator
from markdownfield.models import MarkdownField, RenderedMarkdownField
from markdownfield.validators import VALIDATOR_STANDARD
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from taggit.managers import TaggableManager
from cloudinary.models import CloudinaryField
from datetime import date
from django.db.models import Count
from taggit.models import Tag

class Category(models.Model):
    name = models.CharField(max_length=200,
                            db_index=True)
    slug = models.SlugField(max_length=200,
                            unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('projects_by_category',
                       args=[self.slug])

class Project(models.Model):
    category = models.ForeignKey(Category,
                                 related_name='projects',
                                 on_delete=models.CASCADE)
    user = models.ForeignKey(User,
                                 related_name='projects',
                                 on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    tags = TaggableManager()
    description = MarkdownField(rendered_field='description_rendered', validator=VALIDATOR_STANDARD, blank=True)
    description_rendered = RenderedMarkdownField()
    video = models.URLField(blank=True)
    goal = models.DecimalField(max_digits=10, decimal_places=2)
    collected_sum = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    expiration_date = models.DateField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    backers = models.PositiveIntegerField(default=0)
    rate = models.FloatField(
        validators=[MinValueValidator(0), MaxValueValidator(5)], default=0
        )
    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('project',
                       args=[self.slug, self.id])

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        self.video = self.video.replace('youtu.be', 'www.youtube.com/embed').replace('watch?v=', 'embed/')
        super(Project, self).save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        super(Project, self).delete(*args, **kwargs)
        Tag.objects.annotate(
                ntag=Count('taggit_taggeditem_items')
            ).filter(ntag=0).delete()

    def days_left(self):
        return (self.expiration_date - date.today()).days

class ProjectImage(models.Model):
    project = models.ForeignKey(Project,
                                related_name='images',
                                on_delete=models.CASCADE)
    image = CloudinaryField('image')

class Reward(models.Model):
    project = models.ForeignKey(Project,
                                related_name='rewards',
                                on_delete=models.CASCADE)
    users = models.ManyToManyField(User,
                                   related_name='rewards',
                                   blank=True)
    name = models.CharField(max_length=200, db_index=True)
    description = models.TextField()
    sum = models.DecimalField(max_digits=10, decimal_places=2)

class Comment(models.Model):
    project = models.ForeignKey(Project,
                             on_delete=models.CASCADE,
                             related_name='comments')
    user = models.ForeignKey(User,
                                 related_name='comments',
                                 on_delete=models.CASCADE)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('created',)

class News(models.Model):
    project = models.ForeignKey(Project,
                             on_delete=models.CASCADE,
                             related_name='news')
    title = models.CharField(max_length=200, db_index=True)
    text = MarkdownField(rendered_field='text_rendered', validator=VALIDATOR_STANDARD, blank=True)
    text_rendered = RenderedMarkdownField()
    image = CloudinaryField('image', null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created',)
        verbose_name = 'news'
        verbose_name_plural = 'news'

    def get_absolute_url(self):
        return reverse('news',
                       args=[self.id])

campaign/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from .forms import ProjectForm, ProjectImageAddForm, RewardForm, CommentForm, NewsForm
from .models import Project, ProjectImage, Reward, Comment, News
from cloudinary.forms import cl_init_js_callbacks     
import decimal

@login_required
def add_project(request):
    if request.method == 'POST':
        form = ProjectForm(request.POST)
        if form.is_valid():
            new_project = form.save(commit=False)
            new_project.user = request.user
            new_project.save()
            form.save_m2m()
            return redirect('edit_project', slug = new_project.slug, id = new_project.id)
    else:
        form = ProjectForm()
    return render(request,
                  'campaign/add_project.html',
                  {'form': form,
                   'title': 'New Project'})

@login_required
def edit_project(request, slug, id):
    project = get_object_or_404(Project, slug = slug, id = id)
    if request.user.id == project.user.id:
        if request.method == 'POST':
            form = ProjectForm(instance=project,
                                     data=request.POST)
            if form.is_valid():
                form.save()
                return redirect(project)
        else:
            form = ProjectForm(instance=project)
        return render(request,
                      'campaign/edit_project.html',
                      {'form': form,
                       'title': 'Edit Project',
                       'project': project})
    else:
        return redirect('home')

def project(request, slug, id):
    project = get_object_or_404(Project, slug = slug, id = id)

    new_comment = None

    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.project = project
            new_comment.user = request.user
            new_comment.save()
    else:
        comment_form = CommentForm()
    return render(request,'campaign/project.html',
                  {'project': project,
                  'title': project.name,
                   'new_comment': new_comment,
                   'comment_form': comment_form,})

@login_required
def add_project_image(request, slug, id):
    project = get_object_or_404(Project,slug = slug, id = id)
    if request.user.id == project.user.id:
        if request.method == 'POST':
            form = ProjectImageAddForm(request.POST, request.FILES)
            if form.is_valid():
                new_project_image = form.save(commit=False)
                new_project_image.project = project
                new_project_image.save()
                form.save()
                return redirect('edit_project', slug = project.slug, id = project.id)
        else:
            form = ProjectImageAddForm()
        return render(request, 'campaign/add_project_image.html',
                      {'form': form,
                       'title': 'Add Image'})
    else:
        return redirect('home')

@login_required
def delete_project_image(request):
    id = request.POST.get('delete_image')
    ProjectImage.objects.get(id=id).delete()
    project = Project.objects.get(id=request.POST.get('project'))
    return redirect('edit_project', slug = project.slug, id = project.id)

@login_required
def add_reward(request, slug, id):
    project = get_object_or_404(Project,slug = slug, id = id)
    if request.user.id == project.user.id:
        if request.method == 'POST':
            form = RewardForm(request.POST)
            if form.is_valid():
                new_reward = form.save(commit=False)
                new_reward.project = project
                new_reward.save()
                return redirect('edit_project', slug = project.slug, id = project.id)
        else:
            form = RewardForm()
        return render(request,
                      'campaign/add_reward.html',
                      {'form': form,
                       'title': 'Add Reward'})
    else:
        return redirect('home')

@login_required
def edit_reward(request, id):
    reward = get_object_or_404(Reward, id = id)
    if request.user.id == reward.project.user.id:
        if request.method == 'POST':
            form = RewardForm(instance=reward,
                                     data=request.POST)
            if form.is_valid():
                form.save()
                return redirect('edit_project', slug = reward.project.slug, id = reward.project.id)
        else:
            form = RewardForm(instance=reward)
        return render(request,
                      'campaign/edit_reward.html',
                      {'form': form,
                       'title': 'Edit Reward',
                       'reward': reward})
    else:
        return redirect('home')

@login_required
def delete_reward(request):
    id = request.POST.get('delete_reward')
    Reward.objects.get(id=id).delete()
    project = Project.objects.get(id=request.POST.get('project'))
    return redirect('edit_project', slug = project.slug, id = project.id)

@login_required
def rewards(request, slug, id):
    project = get_object_or_404(Project, slug=slug, id=id)
    rewards = project.rewards.order_by('sum')
    if request.method == 'POST':
        if 'reward' in request.POST:
            reward_id=request.POST.get('reward')
            reward = Reward.objects.get(id=reward_id)
            reward.users.add(request.user)
            sum = reward.sum  
        elif 'sum' in request.POST:
            sum = decimal.Decimal(request.POST.get('sum'))
        project.backers += 1
        project.collected_sum += sum
        project.save()
        return render(request,
                      'campaign/pledged.html',
                      {'title': 'pledged',
                       'sum': sum})
    return render(request,
                      'campaign/rewards.html',
                      {'title': 'Rewards',
                       'rewards': rewards})


@login_required
def add_news(request, slug, id):
    project = get_object_or_404(Project,slug = slug, id = id)
    if request.user.id == project.user.id:
        if request.method == 'POST':
            form = NewsForm(request.POST, request.FILES)
            if form.is_valid():
                news = form.save(commit=False)
                news.project = project
                news.save()
                form.save()
                return redirect('news', id = news.id)
        else:
            form = NewsForm()
        return render(request, 'campaign/add_news.html',
                      {'form': form,
                       'title': 'Add News'})
    else:
        return redirect('home')

@login_required
def edit_news(request, id):
    news = get_object_or_404(News, id = id)
    if request.user.id == news.project.user.id:
        if request.method == 'POST':
            form = NewsForm(instance=news,
                                     data=request.POST, files=request.FILES)
            if form.is_valid():
                form.save()
                return redirect(news)
        else:
            form = NewsForm(instance=news)
        return render(request,
                      'campaign/edit_news.html',
                      {'form': form,
                       'title': 'Edit News',
                       'news': news})
    else:
        return redirect('home')

def news(request, id):
    news = get_object_or_404(News, id = id)
    if request.method == 'POST' and 'delete_news' in request.POST:
        project = news.project
        News.objects.get(id = id).delete()
        return redirect(project)
    return render(request,'campaign/news.html',
                  {'news': news,
                  'title': news.title,
                   })

campaign/templates/campaign/add_news.html
{% extends "app/layout.html" %}

{% block content %}
    <h2>{{ title }}</h2>
    <section id="newsAddForm">
        <form action="." method="post" enctype="multipart/form-data" class="form-horizontal">
            {% csrf_token %}
            <h4>You can add news using the following form:</h4>
            <hr/>
            <div class="form-group">
                <label for="id_title" class="col-md-2 control-label">News title</label>
                <div class="col-md-10">
                    {{ form.title }}
                </div>
            </div>
            <div class="form-group">
                <label for="id_text" class="col-md-2 control-label">Text</label>
                <div class="col-md-10">
                    {{ form.text}}
                </div>
            </div>
            <div class="form-group">
                <label for="id_image" class="col-md-2 control-label">Image</label>
                <div class="col-md-10">
                    {{ form.image}}
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="hidden" name="next" value="/" />
                    <input type="submit" value="Add" class="btn btn-success" />
                </div>
            </div>
            {% if form.errors %}
                <p class="validation-summary-errors">Please enter correct data.</p>
            {% endif %}
        </form>
    </section>
{% endblock %}

{% block scripts %}
    <script>
        var easyMDE = new EasyMDE();
    </script>
{% endblock %}

campaign/templates/campaign/add_project.html
{% extends "app/layout.html" %}

{% block content %}
    <h2>{{ title }}</h2>
    <section id="projectAddForm">
        <form action="." method="post" class="form-horizontal">
            {% csrf_token %}
            <h4>You can create new project using the following form:</h4>
            <hr/>
            <div class="form-group">
                <label for="id_category" class="col-md-2 control-label">Category</label>
                <div class="col-md-10">
                    {{ form.category }}
                </div>
            </div>
            <div class="form-group">
                <label for="id_name" class="col-md-2 control-label">Project name</label>
                <div class="col-md-10">
                    {{ form.name }}
                </div>
            </div>
            <div class="form-group">
                <label for="id_tags" class="col-md-2 control-label">Tags</label>
                <div class="col-md-10">
                    {{ form.tags }}
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-2">
                    <label for="id_description" class="control-label">Short description</label>
                </div>
                <div class="col-md-10">
                    {{ form.description}}
                </div>
            </div>
            <div class="form-group">
                <label for="id_video" class="col-md-2 control-label">YT video URL</label>
                <div class="col-md-10">
                    {{ form.video}}
                </div>
            </div>
            <div class="form-group">
                <label for="id_goal" class="col-md-2 control-label">Project goal (US$)</label>
                <div class="col-md-10">
                    {{ form.goal}}
                </div>
            </div>
            <div class="form-group">
                <label for="id_expiration_date" class="col-md-2 control-label">Project expiration date</label>
                <div class="col-md-10">
                    {{ form.expiration_date}}
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="hidden" name="next" value="/" />
                    <input type="submit" value="Create project" class="btn btn-success" />
                </div>
            </div>
            {% if form.errors %}
                <p class="validation-summary-errors">Please enter correct data.</p>
            {% endif %}
        </form>
    </section>
{% endblock %}

{% block scripts %}
    <script>
        var easyMDE = new EasyMDE();
    </script>
{% endblock %}

campaign/templates/campaign/add_project_image.html
{% extends "app/layout.html" %}
{% load cloudinary %}

{% block content %} 

    <h2>{{ title }}</h2>
    <section id="projectImageAddForm">
        <form action="." method="post" enctype="multipart/form-data" class="form-horizontal">
            {% csrf_token %}
            <hr/>
            <div class="form-group">
                {{ form.image }}
            </div>
            <div class="form-group">
                <div>
                    <input type="hidden" name="next" value="/" />
                    <input type="submit" value="Upload Image" class="btn btn-default" />
                </div>
            </div>
        </form>
    </section>
    
{% endblock %}

    

campaign/templates/campaign/add_reward.html
{% extends "app/layout.html" %}

{% block content %}
    <h2>{{ title }}</h2>
    <section id="rewardAddForm">
        <form action="." method="post" class="form-horizontal">
            {% csrf_token %}
            <h4>You can add new reward using the following form:</h4>
            <hr/>
            <div class="form-group">
                <label for="id_name" class="col-md-2 control-label">Reward name</label>
                <div class="col-md-10">
                    {{ form.name }}
                </div>
            </div>
            <div class="form-group">
                <label for="id_description" class="col-md-2 control-label">Reward description</label>
                <div class="col-md-10">
                    {{ form.description}}
                </div>
            </div>
            <div class="form-group">
                <label for="id_sum" class="col-md-2 control-label">Sum (US$)</label>
                <div class="col-md-10">
                    {{ form.sum}}
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="hidden" name="next" value="/" />
                    <input type="submit" value="Add Reward" class="btn btn-success" />
                </div>
            </div>
            {% if form.errors %}
                <p class="validation-summary-errors">Please enter correct data.</p>
            {% endif %}
        </form>
    </section>
{% endblock %}

campaign/templates/campaign/edit_news.html
{% extends "app/layout.html" %}

{% block content %}
    <h2>{{ title }}</h2>
    <section id="newsEditForm">
        <form action="." method="post" enctype="multipart/form-data" class="form-horizontal">
            {% csrf_token %}
            <h4>You can edit news using the following form:</h4>
            <hr/>
            <div class="form-group">
                <label for="id_title" class="col-md-2 control-label">News title</label>
                <div class="col-md-10">
                    {{ form.title }}
                </div>
            </div>
            <div class="form-group">
                <label for="id_text" class="col-md-2 control-label">Text</label>
                <div class="col-md-10">
                    {{ form.text}}
                </div>
            </div>
            <div class="form-group">
                <label for="id_image" class="col-md-2 control-label">Image</label>
                <div class="col-md-10">
                    {{ form.image}}
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="hidden" name="next" value="/" />
                    <input type="submit" value="Save" class="btn btn-success" />
                </div>
            </div>
            {% if form.errors %}
                <p class="validation-summary-errors">Please enter correct data.</p>
            {% endif %}
        </form>
    </section>
{% endblock %}

{% block scripts %}
    <script>
        var easyMDE = new EasyMDE();
    </script>
{% endblock %}

campaign/templates/campaign/edit_project.html
{% extends "app/layout.html" %}

{% block content %}
    <h2>{{ title }}</h2>
    <div class="row">
        <div class="col-sm-9">
            <section id="projectEditForm">
                <form action="." method="post" class="form-horizontal">
                    {% csrf_token %}
                    <h4>Edit your project</h4>
                    <hr/>
                    <div class="form-group">
                        <label for="id_category" class="col-md-2 control-label">Category</label>
                        <div class="col-md-10">
                            {{ form.category }}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="id_name" class="col-md-2 control-label">Project name</label>
                        <div class="col-md-10">
                            {{ form.name }}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="id_tags" class="col-md-2 control-label">Tags</label>
                        <div class="col-md-10">
                            {{ form.tags }}
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-2">
                            <label for="id_description" class="control-label">Short description</label>
                        </div>
                        <div class="col-md-10">
                            {{ form.description}}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="id_video" class="col-md-2 control-label">YT video URL</label>
                        <div class="col-md-10">
                            {{ form.video}}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="id_goal" class="col-md-2 control-label">Project goal (US$)</label>
                        <div class="col-md-10">
                            {{ form.goal}}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="id_expiration_date" class="col-md-2 control-label">Project expiration date</label>
                        <div class="col-md-10">
                            {{ form.expiration_date}}
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="hidden" name="next" value="/" />
                            <input type="submit" value="Save" class="btn btn-success" />
                        </div>
                    </div>
                    {% if form.errors %}
                        <p class="validation-summary-errors">Please enter correct data.</p>
                    {% endif %}
                </form>
            </section>
        </div>
        <div class="col-sm-3">
            <section>
                <h4>Images</h4>
                <form action="{% url 'delete_project_image' %}" method="post" class="form-horizontal">
                    {% csrf_token %}
                    {% for image in project.images.all %}
                        <div class="img-wrap">
                            <img src = "{{ image.image.url }}" class="img-responsive" style="margin-bottom:10px"/>
                            <input type="hidden" name="project" value="{{ project.id }}" />
                            <button type="submit" name="delete_image" value="{{ image.id }}" class="btn delete">
                                X
                            </button>
                        </div>
                    {% endfor %}
                </form>
                <a class="btn btn-success" href="{% url 'add_project_image' slug=project.slug id=project.id %}">Add Image</a>
            </section>
            <hr />
            <section>
                <h4>Rewards</h4>
                <form action="{% url 'delete_reward' %}" method="post" class="form-horizontal">
                    {% csrf_token %}
                    {% for reward in project.rewards.all %}
                        <div class="row" style="margin-bottom: 10px">
                            <div class="col-xs-10">
                                <a href="{% url 'edit_reward' id=reward.id %}">{{ reward.name }}</a>
                            </div>
                            <div class="col-xs-2">
                                <input type="hidden" name="project" value="{{ project.id }}" />
                                <button class="btn btn-default" type="submit" name="delete_reward" value="{{ reward.id }}">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </div>
                        </div>
                    {% endfor %}
                </form>
                
                <a class="btn btn-success" href="{% url 'add_reward' slug=project.slug id=project.id %}">Add Reward</a>
            </section>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script>
        var easyMDE = new EasyMDE();
    </script>
{% endblock %}

campaign/templates/campaign/edit_reward.html
{% extends "app/layout.html" %}

{% block content %}
    <h2>{{ title }}</h2>
    <section id="rewardEditForm">
        <form action="." method="post" class="form-horizontal">
            {% csrf_token %}
            <h4>You can edit reward using the following form:</h4>
            <hr/>
            <div class="form-group">
                <label for="id_name" class="col-md-2 control-label">Reward name</label>
                <div class="col-md-10">
                    {{ form.name }}
                </div>
            </div>
            <div class="form-group">
                <label for="id_description" class="col-md-2 control-label">Reward description</label>
                <div class="col-md-10">
                    {{ form.description}}
                </div>
            </div>
            <div class="form-group">
                <label for="id_sum" class="col-md-2 control-label">Sum (US$)</label>
                <div class="col-md-10">
                    {{ form.sum}}
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="hidden" name="next" value="/" />
                    <input type="submit" value="Save" class="btn btn-success" />
                </div>
            </div>
            {% if form.errors %}
                <p class="validation-summary-errors">Please enter correct data.</p>
            {% endif %}
        </form>
    </section>
{% endblock %}

campaign/templates/campaign/news.html
{% extends "app/layout.html" %}

{% block content %}
    <h1>{{ news.title }}</h1>
    {% if news.image.url != null %}
        <img src="{{ news.image.url }}" class="img-responsive" alt="Image">
    {% endif %}
    <div>
        {{ news.text_rendered | safe }}
    </div>
    {% if news.project.user.id == user.id %}
        <form action="." method="post" class="form-horizontal">
            {% csrf_token %}
            <a href="{% url 'edit_news' id=news.id %}" class="btn btn-default">Edit</a>
            <button type="submit" name="delete_news" class="btn btn-danger">Delete</button>
        </form>
    {% endif %}
{% endblock %}

campaign/templates/campaign/pledged.html
{% extends "app/layout.html" %}

{% block content %}
    <h2>You successfully pledged ${{ sum }}!</h2>
{% endblock %}

campaign/templates/campaign/rewards.html
{% extends "app/layout.html" %}

{% block content %}
    <form action="." method="post" class="form-horizontal">
        {% csrf_token %}
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Pledge without a reward</h3>
            </div>
            <div class="panel-body">
                <input type="number" name="sum" placeholder="Sum ($)" step=".01" min="0"
                       class="form-control" style="margin-bottom:10px">
                <button type="submit" class="btn btn-success col-sm-offset-9 col-sm-3">Pledge</button>
            </div>
        </div>
        {% for reward in rewards %}
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">{{ reward.name }}</h3>
                </div>
                <div class="panel-body">
                    <p>{{ reward.description }}</p>
                    <button type="submit" name="reward" value="{{ reward.id }}"
                            class="btn btn-success col-sm-offset-9 col-sm-3">
                        Pledge ${{reward.sum}}
                    </button>
                </div>
            </div>
        {% endfor %}
    </form>
{% endblock %}