Project/urls.py
"""
Definition of urls for Project.
"""

from django.urls import path, include
from django.contrib import admin
from app import views


urlpatterns = [
    path('tag/<slug:tag_slug>/', views.home, name='projects_by_tag'),
    path('category/<slug:category_slug>/', views.home, name='projects_by_category'),
    path('search/', views.home, name='search'),
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('campaign/', include('campaign.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
]

app/forms.py
from django import forms

class OrderByForm(forms.Form):
    FILTER_CHOICES = [
    ('name', 'Name'),
    ('-created', 'Date'),
    ]   
    order_by = forms.ChoiceField(widget=forms.Select(attrs=
                                       {'class': 'form-control',
                                        'onchange': 'orderByForm.submit();'
                                        }),
                          choices=FILTER_CHOICES)

app/templates/app/index.html
{% extends "app/layout.html" %}

{% block nav %}
    <nav class="navbar navbar-default">
        <div class="container">
            <ul class="scroll nav navbar-nav">
                {% for c in categories %}
                    <li {% if category.slug == c.slug %}class="active"{% endif %}>
                        <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </nav>
{% endblock %}

{% block content %}
    <div class="row">
        <form id="orderByForm" method="get" action="." class="pull-right">
            <div class="form-group">
                <label for="id_order_by" class="control-label">Order by</label>
                {{ order_by_form.order_by }}
            </div>
        </form>
    </div>
    <div class="row" style="margin-top:20px">
        <div class="col-sm-2" style="margin-bottom:20px">
            {% for tag in tags %}
                <a href="{% url "projects_by_tag" tag.slug %}">{{tag.name}}</a>
                {% if not forloop.last %}, {% endif %}
            {% endfor %}
        </div>
        <div class="col-sm-10">
            {% for project in projects %}
                <div class="panel panel-default">
                    <div class="panel-body" >
                        <h3><a href="{{ project.get_absolute_url }}">{{ project.name }}</a></h3>
                    </div>
                </div>
            {% empty %}
                <p>There are no such projects.</p>
            {% endfor %}
        </div>
    </div>
{% endblock %}

app/templates/app/layout.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{{ title }} - Project</title>
        {% load static %}
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" type="text/css" href="{% static 'app/content/bootstrap.min.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'app/content/bootstrap-social.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'app/content/site.css' %}" />
        <link rel="stylesheet" href="https://unpkg.com/easymde/dist/easymde.min.css">
        <script src="https://unpkg.com/easymde/dist/easymde.min.js"></script>
        <script src="{% static 'app/scripts/modernizr-2.6.2.js' %}"></script>
    </head>

    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a href="/" class="navbar-brand">Project</a>
                </div>
                <div class="navbar-collapse collapse">
                    <form method="get" action="{% url 'search' %}" class="navbar-form navbar-left">
                        <div class="form-group">
                            <input type="text" name="query" class="form-control" placeholder="Search">
                        </div>
                        <button type="submit" class="btn btn-default">
                            <span class="glyphicon glyphicon-search"></span>
                        </button>
                    </form>
                    {% include 'app/loginpartial.html' %}
                </div>
            </div>
        </div>
        {% block nav %} {% endblock %}

        <div class="container body-content">
            {% block content %}{% endblock %}
            <hr/>
            <footer>
                <p>&copy; Project</p>
            </footer>
        </div>

        <script src="{% static 'app/scripts/jquery-1.10.2.js' %}"></script>
        <script src="{% static 'app/scripts/bootstrap.js' %}"></script>
        <script src="{% static 'app/scripts/respond.js' %}"></script>
        {% block scripts %}{% endblock %}

    </body>
</html>

app/templates/app/loginpartial.html
{% if user.is_authenticated %}
    <form id="logoutForm" action="/account/logout/" method="post" class="navbar-right">
        {% csrf_token %}
        <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
                <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{user.username}} <span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li><a href="{% url 'my_rewards' %}">My Rewards</a></li>
                    <li><a href="{% url 'my_projects' %}">My Projects</a></li>
                    <li><a href="{% url 'my_profile' %}">My Profile</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="{% url "logout" %}">Log out</a></li>
                </ul>
            </li>
        </ul>
    </form>
{% else %}
    <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'login' %}">Log in</a></li>
    </ul>
{% endif %}